name: Auto Bump Version
on:
  workflow_dispatch:
    inputs:
      newversion:
        description: 'npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git]'
        required: true
      preid:
        description: 'The "prerelease identifier" to use as a prefix for the "prerelease" part of a semver.'
        required: false

permissions:
  pull-requests: write
  contents: write

jobs:
  bump:
    name: Bump
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name '${{ secrets.GIT_USER_NAME }}'
          git config user.email '${{ secrets.GIT_USER_EMAIL }}'

      - name: Current version
        run: echo "CURRENT_VERSION=$(jq -r .version < package.json)" >> $GITHUB_ENV

      - name: Bump version
        run: |
          npm version ${{ inputs.newversion }} --preid ${{ inputs.preid }} --git-tag-version false

      - name: New version
        run: echo "NEW_VERSION=$(jq -r .version < package.json)" >> $GITHUB_ENV

      - name: Commit
        run: "git commit -am 'Bump version to ${{ env.NEW_VERSION }}'"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          title: bump version to ${{ env.NEW_VERSION }}
          body: from ${{ env.CURRENT_VERSION }} to ${{ env.NEW_VERSION }}
          reviewers: '${{ github.actor }}'

      - name: Enable auto-merge
        run: gh pr merge --merge --auto "${{ steps.cpr.outputs.pull-request-url }}"

      - name: Approve request
        run: gh pr comment "${{ steps.cpr.outputs.pull-request-url }}" --body "@github-actions approve me"
